FROM registry.heroku.com/langgraph-server/web:latest

COPY langgraph-app /deps/langgraph-app
RUN pip install --no-cache-dir -e /deps/langgraph-app

COPY langgraph-app/langgraph.json /deps/langgraph.json
